/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "DatabaseUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NautikosMainBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "ResendApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "StripeApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "StripeWebhookSigningSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "WebApp": {
      "type": "sst.aws.Remix"
      "url": string
    }
  }
}
